# Generated by Django 4.0.5 on 2022-12-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_tradehistory_settle_amt_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderhistory",
            unique_together={("order_date", "order_no", "account_alias")},
        ),
    ]
