# Generated by Django 4.0.5 on 2023-04-18 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_orderhistory_account_alias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('base_date', models.DateField(max_length=8)),
                ('base_io_krw', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('base_io_usd', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('dividend_usd', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('deposit_interest_krw', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('base_amount_krw', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('account_evaluation_krw', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('account_evaluation_usd', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('stock_evaluation_krw', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('stock_evaluation_usd', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('account_alias', models.ForeignKey(db_column='account_alias', max_length=100,
                                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                                    related_name='account_settlement', to=settings.AUTH_USER_MODEL,
                                                    to_field='username')),
            ],
            options={
                'unique_together': {('base_date', 'account_alias')},
            },
        ),
    ]
