# Generated by Django 4.0.5 on 2023-04-21 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('account_alias', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(
                    choices=[('NORMAL', 'NORMAL'), ('ISA', 'ISA'), ('PENSION', 'PENSION'), ('IRP', 'IRP')],
                    default='NORMAL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(default='', max_length=100, null=True)),
                ('owner', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING,
                                            to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'abstract': False,
            },
        )
    ]
