# Generated by Django 4.0.5 on 2023-04-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='account_alias',
            field=models.ForeignKey(db_column='account_alias', max_length=100,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders',
                                    to='accounts.account', to_field='account_alias'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='account_alias',
            field=models.ForeignKey(db_column='account_alias', max_length=100,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_settlement',
                                    to='accounts.account', to_field='account_alias'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='account_alias',
            field=models.ForeignKey(db_column='account_alias', max_length=100,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='trades',
                                    to='accounts.account', to_field='account_alias'),
        ),
    ]
