# Generated by Django 4.0.5 on 2023-04-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_alter_orderhistory_account_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='account_alias',
            field=models.ForeignKey(db_column='account_alias', max_length=100,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='settlements',
                                    to='accounts.account', to_field='account_alias'),
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('base_date', models.DateField(max_length=8)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
                ('holding_qty', models.IntegerField()),
                ('eval_amt', models.DecimalField(decimal_places=8, max_digits=25, null=True)),
                ('market_price', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('buy_qty', models.IntegerField(default=0)),
                ('sell_qty', models.IntegerField(default=0)),
                ('account_alias', models.ForeignKey(db_column='account_alias', max_length=100,
                                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                                    related_name='holdings', to='accounts.account',
                                                    to_field='account_alias')),
            ],
            options={
                'unique_together': {('base_date', 'account_alias', 'symbol')},
            },
        ),
    ]
