# Generated by Django 4.0.5 on 2023-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_alter_settlement_account_alias_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
    ]
