# Generated by Django 3.1 on 2021-11-21 04:22

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetUniverse",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="created date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="updated date"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="universe name",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="description"),
                ),
                (
                    "symbols",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            help_text="symbol(ticker)", max_length=20
                        ),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="created date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="updated date"),
                ),
                ("symbol", models.CharField(help_text="symbol(ticker)", max_length=20)),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=5, help_text="open price", max_digits=15
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=5, help_text="close price", max_digits=15
                    ),
                ),
                (
                    "adj_close",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Ajd close",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=5, help_text="high price", max_digits=15
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=5, help_text="low price", max_digits=15
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=5, help_text="volume", max_digits=40
                    ),
                ),
                ("base_date", models.DateField(help_text="Base date")),
            ],
            options={
                "ordering": ["-base_date"],
                "unique_together": {("symbol", "base_date")},
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="created date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="updated date"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("E", "ETF"), ("S", "STOCK")], max_length=1
                    ),
                ),
                ("symbol", models.CharField(help_text="symbol(ticker)", max_length=20)),
                ("category", models.CharField(help_text="category", max_length=50)),
                (
                    "sub_category",
                    models.CharField(help_text="sub category", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="description", null=True),
                ),
            ],
            options={
                "unique_together": {
                    ("asset_type", "symbol", "category", "sub_category")
                },
            },
        ),
    ]
