# Generated by Django 4.0.5 on 2022-12-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="market_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
