# Generated by Django 3.1 on 2021-06-19 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='base_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Base date'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together={('symbol', 'base_date')},
        ),
    ]
