# Generated by Django 4.0.5 on 2023-02-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_market_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('symbol', models.CharField(max_length=10)),
                ('total_returns', models.DecimalField(decimal_places=3, help_text='high price', max_digits=8)),
                ('daily_volatility', models.DecimalField(decimal_places=3, help_text='high price', max_digits=8)),
                ('sharp_ratio', models.DecimalField(decimal_places=3, help_text='high price', max_digits=8)),
                ('beta', models.DecimalField(decimal_places=3, help_text='high price', max_digits=8)),
                ('cumulative_returns', models.DecimalField(decimal_places=3, help_text='high price', max_digits=8)),
                ('monthly_volatility', models.DecimalField(decimal_places=3, help_text='high price', max_digits=8)),
                ('base_date', models.DateField(help_text='base_date')),
                ('period', models.CharField(choices=[('3M', '3Month'), ('6M', '6Month'), ('1Y', '1Year'), ('2Y', '2Year')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
