# Generated by Django 3.1 on 2021-06-30 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_update_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUniverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('universe_id', models.UUIDField(default=uuid.uuid4)),
                ('symbol', models.CharField(help_text='symbol(ticker)', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
