# Generated by Django 4.0.5 on 2023-02-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCorrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('symbol', models.CharField(max_length=10)),
                ('correlation', models.JSONField(null=True)),
                ('distance', models.JSONField(null=True)),
                ('base_date', models.DateField(help_text='base_date')),
                ('period', models.CharField(choices=[('3M', '3Month'), ('6M', '6Month'), ('1Y', '1Year'), ('2Y', '2Year')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
