# Generated by Django 3.1 on 2021-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetuniverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='adj_close',
            field=models.DecimalField(decimal_places=5, help_text='Ajd close', max_digits=15, null=True),
        ),
    ]
