# Generated by Django 3.1 on 2021-08-15 11:42

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_set_adj_close_allow_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprice',
            options={'ordering': ['-base_date']},
        ),
        migrations.RemoveField(
            model_name='assetuniverse',
            name='symbol',
        ),
        migrations.AddField(
            model_name='assetuniverse',
            name='description',
            field=models.TextField(default='', help_text='description'),
        ),
        migrations.AddField(
            model_name='assetuniverse',
            name='name',
            field=models.CharField(default='', help_text='universe name', max_length=100),
        ),
        migrations.AddField(
            model_name='assetuniverse',
            name='symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='symbol(ticker)', max_length=20), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='assetuniverse',
            name='id',
        ),
        migrations.AddField(
            model_name='assetuniverse',
            name='universe_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        )
    ]
