# Generated by Django 3.1 on 2021-09-03 14:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="created date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="updated date"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("weights", models.JSONField(help_text="weights")),
                ("base_date", models.DateField(help_text="base_date")),
                (
                    "description",
                    models.TextField(default="", help_text="portfolio description"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
