# Generated by Django 4.0.5 on 2023-01-11 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="created date"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="updated date"),
                ),
                ("currency_code", models.CharField(max_length=10)),
                ("currency_name", models.CharField(max_length=50)),
                (
                    "base_date",
                    models.DateField(
                        default=datetime.datetime(2023, 1, 11, 12, 29, 15, 805551)
                    ),
                ),
                (
                    "sending_exchange_rate",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "receiving_exchange_rate",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "trading_exchange_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="매매기준율", max_digits=15
                    ),
                ),
                (
                    "book_exchange_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="장부가격", max_digits=15
                    ),
                ),
                (
                    "kor_book_exchange_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="서울외국환중개장부가격",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "kor_trading_exchange_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="서울외국환매매기준율",
                        max_digits=15,
                        null=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("currency_code", "base_date")},
            },
        ),
    ]
