# Generated by Django 3.1 on 2021-05-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='symbol(ticker)', max_length=20)),
                ('open', models.DecimalField(decimal_places=5, help_text='open price', max_digits=15)),
                ('close', models.DecimalField(decimal_places=5, help_text='close price', max_digits=15)),
                ('adj_close', models.DecimalField(decimal_places=5, help_text='Ajd close', max_digits=15)),
                ('high', models.DecimalField(decimal_places=5, help_text='high price', max_digits=15)),
                ('low', models.DecimalField(decimal_places=5, help_text='low price', max_digits=15)),
                ('volume', models.DecimalField(decimal_places=5, help_text='volume', max_digits=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
            ],
        ),
    ]
