# Generated by Django 3.1 on 2021-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('asset_type', models.CharField(choices=[('E', 'ETF'), ('S', 'STOCK')], max_length=1)),
                ('symbol', models.CharField(help_text='symbol(ticker)', max_length=20)),
                ('category', models.CharField(help_text='category', max_length=50)),
                ('sub_category', models.CharField(help_text='sub category', max_length=100)),
                ('description', models.TextField(blank=True, help_text='description', null=True)),
            ],
            options={
                'unique_together': {('asset_type', 'symbol', 'category', 'sub_category')},
            },
        ),
    ]
