# Generated by Django 4.0.5 on 2022-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('account_alias', models.CharField(max_length=100)),
                ('order_date', models.DateField(max_length=8)),
                ('order_branch_no', models.CharField(blank=True, default='', max_length=10)),
                ('order_no', models.CharField(blank=True, default='', max_length=10)),
                ('origin_order_no', models.CharField(blank=True, default='', max_length=10)),
                ('trade_type', models.CharField(blank=True, default='', max_length=2)),
                ('trade_type_name', models.CharField(blank=True, default='', max_length=8)),
                ('cancel_code', models.CharField(blank=True, default='', max_length=2)),
                ('cancel_code_name', models.CharField(blank=True, default='', max_length=8)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('ord_qty', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('exec_qty', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('ord_price', models.DecimalField(decimal_places=8, max_digits=25, null=True)),
                ('exec_price', models.DecimalField(decimal_places=8, max_digits=25, null=True)),
                ('exec_amt', models.DecimalField(decimal_places=8, max_digits=25, null=True)),
                ('unexec_qty', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('status_name', models.CharField(blank=True, default='', max_length=200)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=200)),
                ('order_time', models.CharField(blank=True, default='', max_length=6)),
                ('market_name', models.CharField(blank=True, default='', max_length=20)),
                ('nation_code', models.CharField(blank=True, default='', max_length=20)),
                ('nation_name', models.CharField(blank=True, default='', max_length=20)),
                ('market_code', models.CharField(blank=True, default='', max_length=20)),
                ('currency_code', models.CharField(blank=True, default='', max_length=20)),
                ('order_date_kst', models.DateField(null=True)),
                ('order_time_kst', models.CharField(blank=True, default='', max_length=6)),
                ('loan_code', models.CharField(blank=True, default='', max_length=2)),
                ('channel', models.CharField(blank=True, default='', max_length=20)),
                ('loan_date', models.CharField(blank=True, default='', max_length=20)),
                ('reject_reason_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
